name: cosign-git-poc
on: push

jobs:
  poc:
    runs-on: ubuntu-latest
    env:
      COSIGN_PASSWORD: ${{ secrets.COSIGN_KEY_PASSWORD }}
    name: poc
    steps:
      - uses: actions/checkout@v2
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
      - name: Check install!
        run: cosign version
      - name: Echo commit SHA
        run: echo $GITHUB_SHA
      - name: Sign HEAD commit
        run: echo -n $COSIGN_PASSWORD | COSIGN_EXPERIMENTAL=1 cosign sign-blob -key $GITHUB_WORKSPACE/cosign.key <(echo -n $GITHUB_SHA)
